---
author:
  firstname: Karthik
  lastname: Thrikkadeeri
  position: "PhD Student, Montaño Lab"
  address: "Louisiana State University, USA"
  contacts:
    - icon: fa envelope
      text: "rikudoukarthik@gmail.com"
      url: "mailto:rikudoukarthik@gmail.com"
    - icon: assets/icon/bi-house-fill.svg
      text: kartrick.com
      url: https://kartrick.com
    - icon: fa brands github
      text: GitHub
      url: https://github.com/rikudoukarthik
    - icon: fa brands orcid
      text: ORCiD
      url: https://orcid.org/0000-0003-2863-5879
    # - icon: fa brands linkedin
    #   text: LinkedIn
    #   url: https://linkedin.com/in/example
    # - icon: fa brands bluesky
    #   text: Bluesky
    #   url: https://bsky.app/profile/kartrick.bsky.social
profile-photo: "cvpic.jpg"
# date: "`r format(Sys.time(), format = '%B %Y')`"
style:
   color-accent: "A92330"
   font-text: "Libertinus Serif"
   font-header: "Petrona"
linkcolor: "66151D"
format:
  awesomecv-typst
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
# library(vitae)
library(tidyverse)
library(glue)
# library(rorcid)
library(lubridate)
```

# Personal Information

**Date of Birth:** 24 March 1999  
**Sex:** Male (he/him)  
**Nationality:** Indian  
**Driving Licence:** LMV & MCWG (India), Class E (USA)  
**Languages:** English, Malayalam (native), Hindi  

### Interests

- Ecological research (community ecology, macroecology, biogeography)
- Data analysis and visualisation ([fun data projects](https://kartrick.com/sandbox/))
- Birdwatching ([eBird profile](https://ebird.org/profile/ODQxNTky))
- Poetry and creative non-fiction writing
- Hip-hop

# Education

### Degrees

{{< yaml assets/yml/education-deg.yml >}}

### Courses/workshops

{{< yaml assets/yml/education-courses.yml >}}

# Certifications

{{< yaml assets/yml/certifications.yml >}}

# Awards

```{=typst}
#resume-entry(
  title: "Rector's Award",
  location: "České Budějovice, CZ",
  date: "2021",
  description: "University of South Bohemia, 25 May 2021",
)
#resume-item[
  - CZK 2,500 (~€100), for outstanding results in study
]

#resume-entry(
  title: "Graduate study Merit Scholarship",
  location: "České Budějovice, CZ",
  date: "2020",
  description: "University of South Bohemia, Oct 2020--May 2021",
)
#resume-item[
  - CZK 1,500 (~€60) awarded per month for 10 months in second year of study
  - Scholarship of the Ministry of Education, Youth and Sports
]
```

# Publications

### Research articles

<!-- This can be selected publications, so manually enter. Particularly since space is limited and need to highlight my name. -->

1. A Viswanathan, **K Thrikkadeeri**, et al. (2025). State of India’s Birds 2023: A framework to leverage semi-structured citizen science for bird conservation. *Ecosphere* 16(7). DOI: https://doi.org/10.1002/ecs2.70290
1. **K Thrikkadeeri** & A Viswanathan (2024). Despite short-lived changes, COVID-19 pandemic had minimal large-scale impact on citizen science participation in India. *Ornithological Applications* 126(4). DOI: https://doi.org/10.1093/ornithapp/duae024 
1. **K Thrikkadeeri**, ..., A Viswanathan (2024). Birdwatchers piecing together Locustella jigsaw: Insights on the wintering distribution of the cryptic West Himalayan Bush Warbler *Locustella kashmirensis*. *Indian BIRDS* 20(3). 
1. L Schillé, ..., **K Thrikkadeeri**, et al. (2024). Latitudinal gradient in avian insectivory: complementary effects of climate, habitat and bird diversity. *Journal of Biogeography* 51(6). DOI: https://doi.org/10.1111/jbi.14808 
1. J Praveen, ..., **K Thrikkadeeri**, et al. (2022). Kerala Bird Atlas 2015--20: features, outcomes and implications of a citizen-science project. *Current Science* 122(3). 

### Software

1. **K Thrikkadeeri** (2024). *skimmr: Working with eBird data made easy*. R package version 0.0.0.9005. URL: https://rikudoukarthik.github.io/skimmr/

### Reports

1. **SoIB** (2023). *State of India's Birds, 2023: Range, trends, and conservation status*. The SoIB Partnership. Pp. 119. DOI: https://doi.org/10.5281/zenodo.11124590 

### Books 

1. PU Antony, ..., **K Thrikkadeeri**, et al. (2018). *Butterflies of Christ University Main Campus---A Pictorial Guide*. Centre for Publications, Christ University, Bangalore, India. 

### In pipeline

1. **K Thrikkadeeri** and A Viswanathan *(in prep.)*. No evidence at large scale for “return” of bird life in the Indian anthropause.
1. **K Thrikkadeeri**, I Freiberga, LR Jorge, K Sam *(in prep.)*. Post-breeding birds dynamically track habitat structure over the season in a Central European forest.
1. **K Thrikkadeeri**, ..., G Shahabuddin *(in prep.)*. A checklist of butterflies from a land-use intensification gradient in Kumaon Himalayas.



# Skills

### Field

- Point counts, line transects, all-out/opportunistic search
- Sound recording (birds), telephoto photography (birds), macro photography
- Camera trapping, PCQ vegetation sampling, radio telemetry 
- Excellent sight and sound ID of birds (India, Europe)
- Extensive field experience in diverse and challenging landscapes, habitats and terrains

### Technical

- Quantitative ecology and research design
- Data curation, management, processing and wrangling
- Reproducibility, version control and transparency in research workflows
- Copy editing and proofreading (English)

### Software

- R, R/Quarto Markdown & allies, Git/GitHub, QGIS
- ChatGPT, Bard
- Audacity, MS Office, Google Suite, Canva, ImageJ 

### Personal qualities

- Ambitious, patient, persistent, self-motivated, time management skills

# Work Experience

{{< yaml assets/yml/work.yml >}}

# Teaching

### Courses

{{< yaml assets/yml/teaching-courses.yml >}}

### Workshops

{{< yaml assets/yml/teaching-workshops.yml >}}

# Presentations

<!-- ### Contributed -->

**2023:** *Citizen Science at NCF Field Sites*. Presented with Mittal Gala. NCF Annual Meet 2023, Mysuru, IN.

**2022:** *The impact of the COVID-19 pandemic on birding and birds in India*. NCF Annual Meet 2022, Mysuru, IN. ([See slides or code](https://kartrick.com/slides/2022_ncf-am_covid-ebirding/))

**2022:** *The impact of the COVID-19 pandemic on birding and birds in India*. International Ornithological Congress 2022, online. ([See slides or code](https://kartrick.com/slides/2022_ioc-covid-ebirding/))

**2022:** *The impact of the COVID-19 pandemic on bird monitoring in India* (poster). Bird Monitoring Symposium 2022, online.

**2019:** *Inventory of butterfly species along a land-use intensification gradient in moist temperate forest biome in Kumaon Himalayas*. Ecology Seminar, University of South Bohemia, CZ.

**2018:** *A study on avian diversity in an industrial area of the Palghat Gap*. National Seminar on Development and Ecological Sustainability: Issues in Emerging India (DESIEI) 2018, Bengaluru, IN.

<!-- ### Public -->

# Field Activities

{{< yaml assets/yml/field-activities.yml >}}

# Other Activities

### Organisational

{{< yaml assets/yml/other-activities-org.yml >}}

### Volunteering

{{< yaml assets/yml/other-activities-vol.yml >}}

### Administrative

{{< yaml assets/yml/other-activities-adm.yml >}}

# Mentoring

- **Vyom Vyas:** Assisted in designing a behavioural study on the breeding ecology of Purple Sunbird

{{< pagebreak >}}

# Referees

**Dr Ashwin Viswanathan**

Research Associate, Education and Public Engagement  
Nature Conservation Foundation, Mysuru, India  
Email: ashwinv@ncf-india.org  

**Dr Suhel Quader**

Scientist, Education and Public Engagement  
Nature Conservation Foundation, Mysuru, India  
Email: suhelq@ncf-india.org  

**Praveen J**

Scientist, Education and Public Engagement  
Nature Conservation Foundation, Mysuru, India  
Email: praveen.j@ncf-india.org  

**Mgr Katerina Sam, PhD**

Head, Laboratory of Multitrophic Interactions  
Biology Centre of the Czech Academy of Sciences, České Budějovice, Czech Republic  
Email: katerinatvardikova@gmail.com  

**Dr PU Antony**

Retired Professor, Department of Zoology  
Christ University, Bengaluru, India  
Email: antonypulahannan@gmail.com  
