---
name: Gol 
surname: D. Roger
qualifications: One Piece
position: "Pirate King"
address: ""
phone: 
profilepic: 
www: 
email: "goldroger@onepiece.com"
twitter: 
linkedin: 
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: e50000
output: vitae::awesomecv
output_format: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)
library(glue)
library(reprex)
```

# Skills

\begin{tabbing}

\textbf{Piracy skills:} \hspace{1cm} \= Basic knowledge of sailing, combat, looting, fleeing \\
\textbf{Identification skills:} \> Experience with haki 

\end{tabbing}


# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where, ~Details, 
  "Senior Secondary Education", "1414-16", "XYZ School", "South Blue", NA,
  "BSc in Piracy", "1416-19", "GDR University", "North Blue", NA,
  "MSc in Cartography", "1419-present", "University of South Blue", "All Blue", NA
) %>% 
  detailed_entries(Degree, Year, Institution, Where, Details)
```


# Publications

## Books 
```{r}
tibble(
    title = "A Pictorial Guide to Guiding",
    author = "GD Roger, et al.",
    journal = "",
    number = " ",
    cites = 0,
    year = "1418",
    cid = NA,
    pubid = NA
    ) %>% 
  detailed_entries(
    what = author,
    when = year,
    with = title,
    ) 
```
## Abstracts
```{r}
  tibble(
    title = "A Study on Studying the Effects of Piracy",
    author = "GD Roger, S Rayleigh",
    journal = "Race to Raftel-1418",
    number = " ",
    cites = 0,
    year = "1418",
    cid = NA,
    pubid = NA
  ) %>% 
  arrange(desc(year)) %>%
  detailed_entries(
    what = author,
    when = year,
    with = title,
    where = journal
  )
```